# 🔢 Basic Numpy Tutorial
This notebook introduces **NumPy**, the fundamental package for numerical computing in Python.
We'll cover array creation, indexing, reshaping, and basic mathematical operations.

In [2]:
import numpy as np

## 1️⃣ Creating Arrays

In [3]:
# From a Python list
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
# Multi-dimensional array
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Zeros, Ones, and Random arrays
zeros = np.zeros((2,3))
ones = np.ones((3,2))
randoms = np.random.rand(2,2)
zeros, ones, randoms

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[0.29753677, 0.50513995],
        [0.3107121 , 0.14669587]]))

## 2️⃣ Array Properties

In [6]:
arr.shape, arr.dtype, arr.size, arr.ndim

((5,), dtype('int64'), 5, 1)

## 3️⃣ Indexing and Slicing

In [7]:
# Indexing
arr[0], arr[-1]

# Slicing
arr[1:4]

array([2, 3, 4])

## 4️⃣ Reshaping and Combining

In [8]:
a = np.arange(1, 10)
reshaped = a.reshape((3, 3))

b = np.array([[10, 20, 30]])

# Stack arrays vertically and horizontally
v_stack = np.vstack([reshaped, b])
h_stack = np.hstack([reshaped, reshaped])
v_stack, h_stack

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 20, 30]]),
 array([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9]]))

## 5️⃣ Basic Mathematical Operations

In [8]:
# Element-wise operations
arr + 10
arr * 2

# Aggregate functions
arr.sum(), arr.mean(), arr.min(), arr.max(), arr.std()

## 6️⃣ Boolean Masking and Filtering

In [9]:
# Filter elements greater than 3
mask = arr > 3
filtered = arr[mask]
filtered